apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: mariadb
  name: mariadb
  namespace: nextcloud
spec:
  selector:
    matchLabels:
      component: mariadb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.3.15
          ports:
            - containerPort: 3306
          args:
            - --transaction-isolation=READ-COMMITTED
            - --binlog-format=ROW
            - --max-connections=1000
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: db-secrets
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: db-secrets
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: db-secrets
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: db-secrets
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-persistent-storage
      restartPolicy: Always
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc
