apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: nextcloud
type: Opaque
data:
  MYSQL_DATABASE: bmV4dGNsb3Vk  #nextcloud
  MYSQL_USER: bmV4dGNsb3Vk      #nextcloud
  MYSQL_PASSWORD: VGVzdGluZzEyM0AxMjMK  #Testing123@123
  MYSQL_ROOT_PASSWORD: VGVzdGluZzEyM0AxMjMK #Testing123@123
# ===linux base64===
# 加密：echo "123456" | base64 -w 0
# 解密：echo MTIzNDU2Cg== | base64 -d 
