apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: nextcloud
  name: nextcloud
  namespace: nextcloud
spec:
  selector:
    matchLabels:
      component: nextcloud
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: nextcloud
    spec:
      containers:
        - image: nextcloud:apache
          imagePullPolicy: IfNotPresent
          name: nextcloud
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_HOST
              value: mariadb:3306
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: db-secrets
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: db-secrets
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: db-secrets
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-persistent-storage
      restartPolicy: Always
      volumes:
        - name: nextcloud-persistent-storage
          persistentVolumeClaim:
            claimName: nextcloud-pvc
