apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/k8s-nginx
    server: 10.20.80.206
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: ailab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;

    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;

    events {
      worker_connections 1024;
    }


    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
  
      log_format proxy_format '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"';
  
      access_log /var/log/nginx/access.log proxy_format;
  
      sendfile on;
      keepalive_timeout 65;
      client_max_body_size 50m;
  
      gzip  on;
      server {
        listen 80;
        #server_name 172.32.88.26;
        rewrite ^(.*) https://$server_name$1 permanent;
        }
      server {
        listen 443 ssl;
        #server_name 172.32.88.26;
        ssl on;
        ssl_certificate /data/tls.crt;
        ssl_certificate_key /data/tls.key;
        access_log /var/log/nginx/access.log proxy_format;
        error_log /var/log/nginx/error.log ; 
    
        location ~^/ailab {
          proxy_pass http://jupyterhub.ailab.svc.cluster.local:8000;
          #root /usr/share/nginx/html;
            
        }
    
        location / {
          #proxy_pass http://172.32.88.26:8000;
            root /usr/share/nginx/html;
        } 
    
      }
      include /etc/nginx/conf.d/*.conf;
    }
kind: ConfigMap
metadata:
  name: nginx-cm
  namespace: ailab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: ailab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: registry.cn-zhangjiakou.aliyuncs.com/lijianhappiness/nginx_https:tlsv1
          name: nginx
          ports:
            - containerPort: 443
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: daima
              mountPath: /usr/share/nginx/html/
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: nginx-cm
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: daima
          persistentVolumeClaim:
            claimName: nginx-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: ailab
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
      name: https
      nodePort: 30811
    #- port: 80
    #  protocol: TCP
    #  targetPort: 80
    #  name: http
    #  nodePort: 30810
  selector:
    app: nginx
