apiVersion: v1
kind: PersistentVolume
metadata:
  name: example
spec:
  capacity: 
    storage: 1Gi
  accessModes:
  - ReadWriteOnce #单机可读写ReadWriteOnce #多机可读写ReadWriteMany #多机只读ReadOnlyMany 
  persistentVolumeReclaimPolicy: Recycle   #保留Retain #回收Recycle #删除Delete
  nfs:
    path: /data/k8s #nfs服务器的目录
    server: 192.168.100.158
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi